### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/pal-nodejs#1]
* [x] Implement Platform 
* [x] Implement Dom
* [x] Implement MutationObserver
     * [x] Attribute Mutation
     * [x] Content Mutation
     * [x] ChildList Mutation
     * [x] SubTree Mutation
* [x] Test Platform
* [x] Test Dom
* [x] Test MutationObserver
     * [x] Attribute Mutation
     * [x] Content Mutation
     * [x] ChildList Mutation
     * [x] SubTree Mutation

**Comment by JeroenVinke** [comment]
:+1:  :+1:

**Comment by EisenbergEffect** [comment]
@martingust You've got some help from the community when you are ready to work on server render.

**Comment by MeirionHughes** [comment]
right so I've got the mutation stuff starting to work for the nodeValue and attribute changes at least. I noticed an odd problem though; 

```
      var target = dom.createElement("div");
      target.nodeValue = "foo";
      target.nodeValue === null; // true;
```
is that correct behavior? a few examples say I should be able to edit the nodeValue; but with jsdom it seems to end up being null regardless. If I do `dom.createTextNode("foo");` then nodeValue is set and I can edit it.

**Comment by MeirionHughes** [comment]
I've had to make a ugly hack to override the prototypes during the PAL initialization: 
 ```
initializePAL((platform, feature, dom) => {
    Object.assign(platform, PLATFORM);  
    Object.setPrototypeOf(platform, PLATFORM.constructor.prototype);       
    Object.assign(dom, DOM);
    Object.setPrototypeOf(dom, DOM.constructor.prototype);
```
without this, the methods simply don't exist on `dom, etc..` and dependents fail when attempting to call them.

**Comment by MeirionHughes** [comment]
if you can live without mutation of child-list and sub-tree, this would appear to be working; `aurelia-templaing-binding` is at least all working with this pal loaded.

**Comment by EisenbergEffect** [comment]
I think that's reasonable. It's not likely needed for server rendering and linting. We can also probably find some workaround to make the output correct in server mode by detecting that mode and using an alternate code path. Really awesome work happening here. @martingust definitely check this out :)

**Comment by MeirionHughes** [comment]
Looks like `attachShadow` is missing from jsdom too as it returns undefined.

**Comment by EisenbergEffect** [comment]
That's fine. The platform should just register that as not supporting the feature for now.

**Comment by MeirionHughes** [comment]
One more thing: I don't know what `eachModule` is supposed to do: https://github.com/MeirionHughes/pal-nodejs/blob/master/source/nodejs-platform.ts#L43

**Comment by EisenbergEffect** [comment]
No need to worry about that. The loader will supply an implementation.

**Comment by martingust** [comment]
Very cool @MeirionHughes , will take a look at this!

**Comment by MeirionHughes** [comment]
You can install it via github if you want to try it. `npm install https://github.com/MeirionHughes/pal-nodejs`. 

I'm currently [using a few of aurelia's components in node-js](https://github.com/MeirionHughes/aurelia-template-lint/blob/master/source/rules/static-type.ts) and it appears to be happy.

**Comment by olanod** [comment]
About jsdom, I think is good for testing, crawlers, static page generation, etc. But I'm not sure about server side rendering and I imagine many people will rely on this to do the server side rendering to later 'activate' the app on the client side. Is it the standard thing to use nowadays? is what other frameworks use as well?

**Comment by MeirionHughes** [comment]
technically I don't think you can do better than to use jsdom in order to get aurelia actually working within the node.js thread. 

As for server-side rendering; I don't know enough about it to make an informed opinion; that said, if this process is serialisation and communication between client<->server, it is isn't all that much more involving to make it client<->server<->chromium. the issue would be

**Comment by EisenbergEffect** [comment]
I don't see why jsdom would be a problem at all. It seems to be the most sensible choice.

**Comment by MeirionHughes** [comment]
Might be better to replace my half-baked attempt at mutation observer with this shim: https://github.com/megawac/MutationObserver.js

I will PR when I get a chance.

**Comment by MeirionHughes** [comment]
Unfortunately looks like there is [a bug with the polyfill](https://github.com/megawac/MutationObserver.js/issues/27) in that it doesn't fire mutation events for text node changes. child-list changes work well though. :D

Also tried polymer's MutationObserver polyfill, but it doesn't want to work (or I'm missing something).

**Comment by devanp92** [comment]
@MeirionHughes Do you think that this might be a better approach:

Something like

```
import {jsdom} from 'jsdom';
import {fs} from 'fs';
...

const mutationObserver = fs.readFileSync('./mutationobserver.js'); //Polymer Polyfill
jsdom.env({
    src: [mutationObserver],
    done: (err, window) => {
        _global = window;
    }
});
``` 

I believe that  ```window``` would contain MutationObserver.

In [the example on jsdom's README](https://github.com/tmpvar/jsdom#easymode-jsdomenv), they pass in jQuery as an external resource to be used with jsDom.

**Comment by MeirionHughes** [comment]
I do believe we're done.

**Comment by niieani** [comment]
Awesome!
