### ISSUE TITLE
Support ShadowDOM

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/pal-nodejs#13]
It should be possible to integrate the Shadow DOM polyfill into this repository and clean up any hacks (i.e. we can create as many document roots as needed with jsdom)

Not currently a priority. 
### resources

**polyfill:** https://github.com/webcomponents/webcomponentsjs

**Comment by EisenbergEffect** [comment]
Closing this out since JSDOM added support for Shadow DOM 😄
