### ISSUE TITLE
SVGElement is not properly polyfilled

### ISSUE THREAD

**Issue by niieani** [aurelia/pal-nodejs#17]
It's not implemented in JSDOM :(

https://github.com/tmpvar/jsdom/issues/1423

We should at least make it an fallback to an empty class for now, cause I'm getting unhandled rejections now from aurelia-binding that does `instanceof SVGElement` checks:

```
<rejected> TypeError: Right-hand side of 'instanceof' is not an object
    at ObserverLocator.getAccessor (./node_modules/aurelia-binding/dist/commonjs/aurelia-binding.js:4612:59)
```

**Comment by EisenbergEffect** [comment]
Can you submit a PR with your recommendation?

**Comment by niieani** [comment]
Yeah, I'll try. Maybe we can make a simple implementation like in this article: https://www.smashingmagazine.com/2014/05/love-generating-svg-javascript-move-to-server/#jsdom
It won't be complete, but it will be better than nothing.

**Comment by EisenbergEffect** [comment]
Sure. It can be added to pal-nodejs.

**Comment by niieani** [comment]
Actually, I see [there's a PR](https://github.com/tmpvar/jsdom/pull/1445) with (incomplete) SVGElement support sitting in the JSDOM repo. 

As long as we're going with our own fork of JSDOM anyway, we could probably merge that, or maybe even complete the implementation, if its not too much work and send a new PR to the maintainers.

**Comment by EisenbergEffect** [comment]
It's worth looking into.

**Comment by niieani** [comment]
Temporary remedy for getting server-side stuff to load, but not a real fix: https://github.com/aurelia/pal-nodejs/pull/18

**Comment by niieani** [comment]
I'm gonna reopen and rename this issue, since we don't have a proper fix yet.

**Comment by Alexander-Taran** [comment]
May be relevant: A Better SVG implementation https://github.com/jsdom/jsdom/pull/2011, which is merged novemer 11, before ~11.5 version lock for jsdom for pal-nodejs

**Comment by Alexander-Taran** [comment]
@niieani can you check jsdom update?

**Comment by niieani** [comment]
I believe @MeirionHughes might have better context for this.

**Comment by EisenbergEffect** [comment]
Closing this since jsdom merged an SVG implementation.
