### ISSUE TITLE
JSDOM private _core api is not available anymore

### ISSUE THREAD

**Issue by zewa666** [aurelia/pal-nodejs#24]
With a recent update of [JSDOM](https://github.com/tmpvar/jsdom/pull/2098) the public api `window._core` we've been using [here](https://github.com/aurelia/pal-nodejs/blob/d2f747dc740af46c847169a73bcbe7051dd664d4/src/nodejs-pal-builder.ts#L67) and [here](https://github.com/aurelia/pal-nodejs/blob/d2f747dc740af46c847169a73bcbe7051dd664d4/src/nodejs-pal-builder.ts#L76) has been removed

**Comment by bondib** [comment]
+1

**Comment by jereckley** [comment]
+1

**Comment by dkent600** [comment]
+1

**Comment by jereckley** [comment]
Any update on this? I can't run any tests...

**Comment by dkent600** [comment]
@jereckley The workaround given [here ](https://github.com/aurelia/pal-nodejs/pull/25) works.

**Comment by bondib** [comment]
You can workaround it  - install "jsdom": "~11.5.1"
It will fix the issue

**Comment by jereckley** [comment]
lol... I was trying to shrinkwrap the npm module. Your right just updating the projects package.json worked great. Thanks!

**Comment by bondib** [comment]
Wasted a few hours on this myself so - sure, np :-)

**Comment by EisenbergEffect** [comment]
Fix is going out in a few minutes. Please stand by and thanks for your patience!

**Comment by EisenbergEffect** [comment]
Released at 1.0.0-beta.3.0.0. @zewa666 Do you think we can make this an official 1.0 with the next release?

**Comment by shabalin** [comment]
Guys, `nodejs-pal-builder.js` still refers to _core:
```javascript
function patchNotifyChange(window) {
 ...
   let node_proto = window._core.Node.prototype;
...
    let char_proto = window._core.CharacterData.prototype;
...
    let element_proto = window._core.Element.prototype;
}
```
which cause the following error when using jsdom@latest:
```
    TypeError: Cannot read property 'Node' of undefined
      at patchNotifyChange (node_modules/aurelia-pal-nodejs/dist/nodejs-pal-builder.js:55:35)
      at Object.buildPal (node_modules/aurelia-pal-nodejs/dist/nodejs-pal-builder.js:14:9)
      at initialize (node_modules/aurelia-pal-nodejs/dist/index.js:14:36)
      at Object.globalize (node_modules/aurelia-pal-nodejs/dist/index.js:73:5)
      at Object.<anonymous> (test/components/jest-pre.ts:8:22)
```

**Comment by zewa666** [comment]
It does, this workaround was just to lock down the jsdom version to where _core still existed. @fkleuver and @EisenbergEffect I think we still need a proper rewrite for this and update to the new APIs
