### ISSUE TITLE
NodeList not available in context of testing with Jest

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/pal-nodejs#29]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.5.0

* **NPM Version:**
yarn 1.3.2

* **Language:**
TypeScript 2.7.1

**Current behavior:**
https://github.com/aurelia/testing/blob/b0fb939fa40f1067ac72d84c7775088f8b8068a6/src/wait.ts#L27
When tests are run with jest  there is no instanceof NodeList. 
It is though under global.window, not under global though.
So even though the element is successfully found by waitForElement - it is not returned. 

* **What is the expected behavior?**
waitForElement returns an element when using Jest to run tests.

* **What is the motivation / use case for changing the behavior?**
being able to waitForElement in tests

can be closed with https://github.com/aurelia/pal-nodejs/pull/28

same issue in testing repo https://github.com/aurelia/testing/issues/83

**Comment by EisenbergEffect** [comment]
Released!

**Comment by Alexander-Taran** [comment]
Well done (-:
