### ISSUE TITLE
Not writable "undefined" property with jsdom 19

### ISSUE THREAD

**Issue by strepon** [aurelia/pal-nodejs#50]
**I'm submitting a bug report**

* **Library Version:**
3.0.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Ubuntu 23.04)

* **Node Version:**
18.16.1

* **NPM Version:**
9.5.1

**Current behavior:**
After upgrading aurelia-pal-nodejs from 2.0.0 (with jsdom 15) to 3.0.0-rc.1 (with jsdom 19), my components tests using `aurelia-testing` stopped to work because the initialization of `ComponentTester` (its `create` method) fails with: ` TypeError: Cannot assign to read only property 'undefined' of object '#<Object>'` at [this line](https://github.com/aurelia/pal-nodejs/blob/d1ecfffa8b721cb1a5d413ea2e7ebfc3c10a6ad7/src/index.ts#L79).

This happens because of upgraded jsdom package whose version 16 adds not writable `undefined` property to its window.

Is this supposed to work? Or is there maybe anything wrong in my setup?

**Comment by raiseandfall** [comment]
@strepon I had the same issues in my test, and ended up forking the repo with a fix. Please note that my fork also bumps jsdom to 21.1.0.
https://github.com/raiseandfall/aurelia-pal-nodejs

**Comment by strepon** [comment]
Thanks for the information and the fix, I confirm that it works for me as well. Did you consider to submit a pull request to this original repo, at least with the fix (without the jsdom update)?
