### ISSUE TITLE
🙏 Update dependencies and release the version

### ISSUE THREAD

**Issue by glyad** [aurelia/pal-nodejs#52]
Dear @bigopon , we, users of Aurelia 1, would be very grateful, if you could release the final version of the package. BTW, it would be great to update all dependencies to the latest versions. 

Thank you in advance,
🙏

**Comment by bigopon** [comment]
Thanks @glyad , I somehow could never got myself to merge the PR until this issue 🙏 
3.0.0-rc.2 is out, it's probably inconvenient but let's wait a bit more before 3.0.0, if there's no more issue within a month or so, we can move into 3.0.0
